import { chromium } from "playwright";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await b.newContext();
await ctx.grantPermissions(["notifications"], { origin: "http://127.0.0.1:8899" });
const p = await ctx.newPage();
const errs = []; p.on("pageerror", e => errs.push(e.message));
await p.goto("http://127.0.0.1:8899/index.html");
await p.waitForSelector(".tt-lesson");
await p.evaluate(() => navigator.serviceWorker.ready);
await p.waitForTimeout(300);
console.log("already granted -> panel hidden on load:", !(await p.locator("#alerts-panel").isVisible()));
console.log("footer note shown:", await p.locator("#reminder-note").isVisible());
console.log("footer reads:", JSON.stringify((await p.textContent(".version")).replace(/\s+/g," ").trim()));
await p.evaluate(async () => {
  window.__notes = [];
  const r = await navigator.serviceWorker.ready;
  const real = r.showNotification.bind(r);
  r.showNotification = (t, o) => { window.__notes.push(t); return real(t, o); };
});
await p.evaluate(() => document.getElementById("alerts-test-footer").scrollIntoView({ block: "center", behavior: "instant" }));
await p.waitForTimeout(250);
await p.click("#alerts-test-footer");
await p.waitForTimeout(400);
console.log("footer test sends:", JSON.stringify(await p.evaluate(() => window.__notes)));
await p.evaluate(() => window.scrollTo(0, 0));
await p.waitForTimeout(300);
await p.keyboard.press("Tab");
console.log("first tab stop:", await p.evaluate(() => document.activeElement.className));
await p.keyboard.press("Enter");
await p.waitForTimeout(800);
console.log("skip link lands on:", await p.evaluate(() => document.activeElement.id || document.activeElement.tagName));
console.log("ERRORS:", errs.length ? errs : "none");
await p.locator(".site-footer").screenshot({ path: "/tmp/views/footer-note.png" });
await b.close();
